name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username
          password: ${{ secrets.DOCKER_TOKEN }}     # DockerHub access token

      # Step 4: Generate Docker image tags based on Semantic Versioning
      - name: Generate Docker image tags
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/angular-site
          tags: |
            type=semver,format={{version}},major={{major}},minor={{major}}.{{minor}},latest

      # Step 5: Build the Docker image (considering the new folder structure)
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-site:${{ steps.metadata.outputs.version }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/angular-site:${{ steps.metadata.outputs.major }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/angular-site:${{ steps.metadata.outputs.minor }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/angular-site:latest \
                       ./angular-site  # Build context is the angular-site folder

      # Step 6: Push Docker images to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-site:${{ steps.metadata.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-site:${{ steps.metadata.outputs.major }}
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-site:${{ steps.metadata.outputs.minor }}
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-site:latest


