name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username
          password: ${{ secrets.DOCKER_TOKEN }}  # DockerHub access token

      # Step 4: Build the Docker image from the Dockerfile
      - name: Check Docker version
        run: docker --version

      - name: Build Docker image
        run: |
          docker info  # Get Docker info for debugging
          docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-site:v1.0 .
          docker images  # Optional: to list built images

      # Step 5: Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-site:v1.0

